{{- if .Values.tdr.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubernetes-agent-tdr-detection
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "kubernetes-agent.labels" . | nindent 4 }}
data:
  http-output.yaml: |
    http_output:
      enabled: true
      url: {{ include "tdr.httpOutputUrl" . | quote }}
{{- end }}
