{{- if and .Values.tdr.enabled (or .Values.tdr.falcoctl.artifact.install.enabled .Values.tdr.falcoctl.artifact.follow.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tdr.name" . }}-falcoctl
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tdr.labels" . | nindent 4 }}
data:
  falcoctl.yaml: |-
    {{- include "tdr.containerPlugin" . -}}
    {{- toYaml .Values.tdr.falcoctl.config | nindent 4 }}
{{- end }}
